version: '3.9'
services:
  react-app:
    build: 
      context: .
    ports:
      - "8080:3000"

  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=f1-storedb
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: https://github.com/etec-integration-project/etec-pi-2024-backend-Santinolopez56.git
      dockerfile: Dockerfile
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=f1-storedb
      - MYSQLDB_HOST=mysqldb
      - MYSQL_USER= root
      - MYSQL_DOCKER_PORT= 3306
    ports:
      - "3000:3000"